#! /bin/bash
#
xcaddy build v2.7.6 --output caddy \
  --with github.com/caddy-dns/cloudflare \
  --with github.com/greenpau/caddy-trace \
  --with github.com/pteich/caddy-tlsconsul \
  --with github.com/greenpau/caddy-security \
  --with github.com/mastercactapus/caddy2-proxyprotocol
  # ratelimit imports go4.org/unsafe/assume-no-moving-gc
  # --with github.com/RussellLuo/caddy-ext/ratelimit
