#! /bin/bash
#
xcaddy build v2.7.6 --output caddy \
  --with github.com/caddy-dns/cloudflare \
  --with github.com/greenpau/caddy-trace \
  --with github.com/pteich/caddy-tlsconsul \
  --with github.com/greenpau/caddy-security
